-- Create the table
CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10, 2) NOT NULL
);

-- Insert seed data
INSERT INTO products (name, description, price) VALUES
('Paracetamol 500mg', 'Analgésico y antipirético comúnmente usado para aliviar dolores leves y reducir fiebre.', 8.99),
('Ibuprofeno 400mg', 'Antiinflamatorio no esteroideo (AINE) que alivia el dolor, fiebre e inflamación.', 12.50),
('Amoxicilina 500mg', 'Antibiótico de amplio espectro usado en infecciones bacterianas.', 18.75),
('Loratadina 10mg', 'Antihistamínico de segunda generación para tratar alergias.', 10.00),
('Omeprazol 20mg', 'Inhibidor de la bomba de protones utilizado para tratar reflujo y úlceras.', 9.50),
('Metformina 850mg', 'Medicamento oral para tratar la diabetes tipo 2.', 13.90),
('Atorvastatina 20mg', 'Usado para reducir los niveles de colesterol LDL.', 16.30),
('Salbutamol Inhalador', 'Broncodilatador utilizado en el tratamiento del asma.', 22.00),
('Clonazepam 0.5mg', 'Medicamento ansiolítico y anticonvulsivante.', 7.80),
('Diclofenaco 50mg', 'Antiinflamatorio para dolores musculares o articulares.', 6.75),
('Aspirina 100mg', 'Analgésico y anticoagulante en dosis baja.', 5.90),
('Azitromicina 500mg', 'Antibiótico usado para tratar diversas infecciones.', 19.20),
('Prednisolona 5mg', 'Corticoide utilizado para inflamaciones severas.', 14.10),
('Cetirizina 10mg', 'Antihistamínico para tratar síntomas de alergias.', 8.20),
('Ranitidina 150mg', 'Inhibidor de ácido estomacal (uso actualmente restringido).', 11.30),
('Fluoxetina 20mg', 'Antidepresivo inhibidor selectivo de recaptación de serotonina (ISRS).', 17.60),
('Loperamida 2mg', 'Tratamiento para la diarrea.', 5.00),
('Naproxeno 500mg', 'Antiinflamatorio para dolor crónico o agudo.', 12.00),
('Levofloxacina 500mg', 'Antibiótico para infecciones bacterianas graves.', 21.00),
('Acetaminofén Infantil', 'Analgésico y antipirético en jarabe para niños.', 9.50),
('Ibuprofeno Infantil', 'Suspensión oral para reducir fiebre y aliviar el dolor en niños.', 7.80),
('Vitamina C 500mg', 'Suplemento antioxidante que contribuye al sistema inmunológico.', 6.50),
('Calcio + Vitamina D3', 'Suplemento para mantener huesos y dientes fuertes.', 12.90),
('Hierro Polimaltosado', 'Tratamiento para la anemia ferropénica.', 11.60),
('Suero Oral', 'Solución para la rehidratación en casos de diarrea o vómito.', 3.50),
('Melatonina 3mg', 'Suplemento para ayudar a regular el sueño.', 9.30),
('Aciclovir 400mg', 'Antiviral utilizado para tratar infecciones por herpes.', 13.20),
('Desloratadina 5mg', 'Antihistamínico para rinitis y urticaria.', 10.70),
('Enalapril 10mg', 'Medicamento antihipertensivo.', 6.90),
('Losartán 50mg', 'Tratamiento para presión arterial alta.', 8.10),
('Furosemida 40mg', 'Diurético para eliminar exceso de líquidos.', 5.40),
('Sal de Rehidratación Oral', 'Sustitución de electrolitos y líquidos en deshidratación.', 2.80),
('Vitamina B12 Inyectable', 'Suplemento para deficiencia de cobalamina.', 15.90),
('Multivitamínico Adulto', 'Fórmula completa de vitaminas y minerales.', 13.50),
('Multivitamínico Infantil', 'Vitaminas en gomitas o jarabe para niños.', 11.00),
('Clorfenamina 4mg', 'Antihistamínico de primera generación.', 4.90),
('Alprazolam 0.25mg', 'Ansiolítico del grupo de las benzodiazepinas.', 8.60),
('Miconazol Óvulos', 'Antifúngico para infecciones vaginales.', 14.30),
('Ketoconazol Shampoo', 'Tratamiento para la caspa y dermatitis seborreica.', 16.00),
('Lidocaína Gel', 'Anestésico local en forma de gel para uso tópico.', 9.40),
('Metoclopramida 10mg', 'Antiemético y procinético para problemas digestivos.', 6.60),
('Clindamicina 300mg', 'Antibiótico para infecciones bacterianas graves.', 18.80),
('Espironolactona 25mg', 'Diurético ahorrador de potasio para tratar hipertensión.', 10.50),
('Carbamazepina 200mg', 'Anticonvulsivante y estabilizador del ánimo.', 17.00),
('Lorazepam 1mg', 'Ansiolítico usado para el tratamiento de la ansiedad.', 9.10),
('Sertralina 50mg', 'Antidepresivo ISRS para trastornos de ansiedad y depresión.', 18.40),
('Valproato de Sodio 500mg', 'Antiepiléptico usado en trastorno bipolar y epilepsia.', 20.60),
('Propranolol 40mg', 'Betabloqueador para taquicardias e hipertensión.', 7.70),
('Risperidona 1mg', 'Antipsicótico atípico para trastornos mentales.', 16.80),
('Budesonida Inhalador', 'Corticoide inhalado para enfermedades respiratorias crónicas.', 24.00);
